import { PrismaClient } from "../src/generated/prisma/client.js";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  // Create admin user
  const hashedPassword = await bcrypt.hash("MilagrosAtibaDestiny3", 12);
  await prisma.user.upsert({
    where: { username: "atibadesouza" },
    update: {},
    create: {
      username: "atibadesouza",
      email: "cooking@atibadesouza.com",
      hashedPassword,
      name: "Atiba de Souza",
      role: "admin",
    },
  });

  // Create categories
  const categoryData = [
    { name: "Appetizers", slug: "appetizers" },
    { name: "Bread", slug: "bread" },
    { name: "Biscuits", slug: "biscuits", parentSlug: "bread" },
    { name: "Sourdough", slug: "sourdough", parentSlug: "bread" },
    { name: "Breakfast", slug: "breakfast" },
    { name: "Desserts", slug: "desserts" },
    { name: "Entrees", slug: "entrees" },
    { name: "Chicken", slug: "chicken", parentSlug: "entrees" },
    { name: "Seafood", slug: "seafood", parentSlug: "entrees" },
    { name: "Salmon", slug: "salmon", parentSlug: "seafood" },
    { name: "Shrimp", slug: "shrimp", parentSlug: "seafood" },
    { name: "Sauces", slug: "sauces" },
    { name: "Sides", slug: "sides" },
    { name: "Rice", slug: "rice", parentSlug: "sides" },
    { name: "Snacks", slug: "snacks" },
    { name: "Vegetarian", slug: "vegetarian" },
    { name: "Mexican", slug: "mexican" },
  ];

  const catMap: Record<string, string> = {};

  // Create parent categories first
  for (const cat of categoryData.filter((c) => !(c as Record<string, string>).parentSlug)) {
    const created = await prisma.category.upsert({
      where: { slug: cat.slug },
      update: { name: cat.name },
      create: { name: cat.name, slug: cat.slug },
    });
    catMap[cat.slug] = created.id;
  }

  // Create child categories
  for (const cat of categoryData.filter((c) => (c as Record<string, string>).parentSlug)) {
    const parentSlug = (cat as Record<string, string>).parentSlug;
    const created = await prisma.category.upsert({
      where: { slug: cat.slug },
      update: { name: cat.name, parentId: catMap[parentSlug] },
      create: {
        name: cat.name,
        slug: cat.slug,
        parentId: catMap[parentSlug],
      },
    });
    catMap[cat.slug] = created.id;
  }

  // Recipe data
  const recipes = [
    {
      title: "No Knead Pull Apart Yeast Dinner Rolls",
      slug: "no-knead-pull-apart-yeast-dinner-rolls",
      description: "Soft, fluffy pull-apart dinner rolls that require no kneading. Perfect for holidays and family dinners.",
      prepTime: "4 hours",
      cookTime: "15 minutes",
      totalTime: "4 hours 15 minutes",
      servings: "12",
      difficulty: "Intermediate",
      cuisine: "American",
      cookingMethod: "Baking",
      ingredients: [
        "1.50 cups warm water",
        "2¼ tsp yeast",
        "2 tsp coarse salt",
        "3¼ cups all-purpose flour",
      ],
      instructions: [
        "Combine water, salt, yeast in a large bowl.",
        "Add flour gradually to achieve pancake batter consistency.",
        "Add remaining flour and mix until no dry patches appear.",
        "Cover and let rise for 2 hours at room temperature.",
        "Punch down dough and shape into rolls, placing them in a greased baking pan.",
        "Let rise for another 1.5-2 hours until doubled.",
        "Bake at 375°F for 15 minutes until golden brown.",
      ],
      categories: ["bread"],
    },
    {
      title: "Authentic Trini Coconut Sweetbread",
      slug: "authentic-trini-coconut-sweetbread",
      description: "A traditional Trinidad Christmas bread that has become an everyday treat. Christmas can't come soon enough. Growing up Sweetbread was a Christmas item...now its EVERYDAY!",
      prepTime: "45 minutes",
      cookTime: "60 minutes",
      totalTime: "1 hour 45 minutes",
      servings: "16",
      difficulty: "Intermediate",
      cuisine: "Caribbean",
      cookingMethod: "Baking",
      ingredients: [
        "3 cups all-purpose flour",
        "1 tablespoon baking powder",
        "½ cup butter, softened",
        "1 cup sugar",
        "2½ cups grated fresh coconut",
        "1 cup raisins",
        "½ cup Paradise cherries, halved",
        "½ cup Paradise mixed peel",
        "1 teaspoon allspice",
        "1 teaspoon nutmeg",
        "2 teaspoons cinnamon",
        "¾ cup whole milk",
        "2 teaspoons vanilla extract",
        "1 egg, beaten",
        "3 tablespoons sugar (for glaze)",
        "1½ tablespoons water (for glaze)",
      ],
      instructions: [
        "Grate fresh coconut (the most labor-intensive step); use white, firm flesh from good coconuts with water inside.",
        "Sift flour and baking powder together in a large bowl.",
        "Cream softened butter and sugar in a separate bowl.",
        "Add coconut, raisins, cherries, mixed peel, allspice, cinnamon, and nutmeg to creamed mixture.",
        "Combine egg, milk, and vanilla extract in a third bowl.",
        "Mix wet ingredients into fruit mixture.",
        "Add flour gradually (¼ cup at a time), mixing thoroughly despite appearing dry.",
        "Grease two 9x5-inch baking pans.",
        "Divide dough evenly between pans.",
        "Press dough to even thickness with spoon back.",
        "Bake at 325°F for 60 minutes until toothpick inserted in center returns clean.",
        "Turn off oven.",
        "Combine 3 tablespoons sugar and 1½ tablespoons water (won't fully dissolve).",
        "Generously baste cooked bread with sugar-water mixture; return to hot (off) oven for 5 minutes.",
      ],
      nutrition: {
        Calories: "361",
        Carbohydrates: "64g",
        Protein: "4g",
        Fat: "11g",
        Fiber: "4.4g",
        Sodium: "70mg",
        Cholesterol: "27mg",
      },
      categories: ["bread"],
    },
    {
      title: "Sourdough Baguettes",
      slug: "sourdough-baguettes",
      description: "Crusty, artisan-style sourdough baguettes with a chewy interior and beautiful crust.",
      prepTime: "30 minutes",
      cookTime: "25 minutes",
      totalTime: "12 hours",
      servings: "3 baguettes",
      difficulty: "Advanced",
      cuisine: "American",
      cookingMethod: "Baking",
      ingredients: [
        "200g active sourdough starter",
        "500g bread flour",
        "325g water",
        "10g salt",
      ],
      instructions: [
        "Mix starter, flour, and water until combined. Rest 30 minutes (autolyse).",
        "Add salt and mix thoroughly.",
        "Perform stretch and folds every 30 minutes for 2 hours.",
        "Bulk ferment for 4-6 hours at room temperature until doubled.",
        "Divide dough into 3 equal pieces.",
        "Pre-shape into logs and rest 20 minutes.",
        "Final shape into baguettes by rolling and tapering ends.",
        "Place on floured couche or baking sheet, seam side up.",
        "Cold proof overnight in refrigerator or proof 1 hour at room temperature.",
        "Score baguettes with a sharp blade at an angle.",
        "Bake at 475°F with steam for 25 minutes until deep golden brown.",
      ],
      categories: ["bread", "sourdough"],
    },
    {
      title: "Sourdough Bagel",
      slug: "sourdough-bagel",
      description: "Chewy, dense sourdough bagels with that perfect New York-style crust.",
      prepTime: "30 minutes",
      cookTime: "25 minutes",
      totalTime: "14 hours",
      servings: "8",
      difficulty: "Intermediate",
      cuisine: "American",
      cookingMethod: "Baking",
      ingredients: [
        "150g active sourdough starter",
        "300g bread flour",
        "150g water",
        "30g honey",
        "8g salt",
        "1 tablespoon barley malt syrup (for boiling)",
      ],
      instructions: [
        "Mix starter, flour, water, honey, and salt into a stiff dough.",
        "Knead for 10 minutes until smooth and elastic.",
        "Bulk ferment for 4-5 hours until puffy.",
        "Divide into 8 pieces (about 80g each).",
        "Shape into balls, poke a hole in the center, and stretch to form bagel shape.",
        "Place on parchment-lined tray. Cold proof overnight in refrigerator.",
        "Bring a large pot of water to boil with barley malt syrup.",
        "Boil bagels for 1 minute each side.",
        "Add toppings (sesame seeds, everything seasoning, etc.).",
        "Bake at 425°F for 20-25 minutes until golden brown.",
      ],
      categories: ["bread", "sourdough"],
    },
    {
      title: "Sourdough Berry Galette",
      slug: "sourdough-berry-galette",
      description: "A rustic, free-form sourdough pastry filled with mixed berries. Beautiful and delicious.",
      prepTime: "30 minutes",
      cookTime: "35 minutes",
      totalTime: "2 hours",
      servings: "8",
      difficulty: "Intermediate",
      cuisine: "American",
      cookingMethod: "Baking",
      ingredients: [
        "100g sourdough discard",
        "200g all-purpose flour",
        "100g cold butter, cubed",
        "50g sugar",
        "Pinch of salt",
        "2-3 tablespoons ice water",
        "3 cups mixed berries",
        "½ cup sugar",
        "2 tablespoons cornstarch",
        "1 tablespoon lemon juice",
        "1 egg (for egg wash)",
        "Coarse sugar for sprinkling",
      ],
      instructions: [
        "Combine flour, sugar, and salt. Cut in cold butter until pea-sized pieces form.",
        "Add sourdough discard and mix. Add ice water as needed to form dough.",
        "Wrap in plastic and refrigerate for 1 hour.",
        "Mix berries with sugar, cornstarch, and lemon juice.",
        "Roll dough into a 12-inch circle on parchment paper.",
        "Spread berry filling in the center, leaving a 2-inch border.",
        "Fold edges over the filling, pleating as you go.",
        "Brush edges with egg wash and sprinkle with coarse sugar.",
        "Bake at 400°F for 35 minutes until golden and bubbly.",
      ],
      categories: ["desserts", "sourdough"],
    },
    {
      title: "Camella's Hot Harvest Ketchup",
      slug: "camellas-hot-harvest-ketchup",
      description: "A homemade ketchup with a spicy kick, perfect for burgers, fries, and everything in between.",
      prepTime: "15 minutes",
      cookTime: "45 minutes",
      totalTime: "1 hour",
      servings: "2 cups",
      difficulty: "Easy",
      cuisine: "American",
      cookingMethod: "Sautee",
      ingredients: [
        "2 lbs ripe tomatoes, chopped",
        "1 onion, diced",
        "2 cloves garlic, minced",
        "½ cup apple cider vinegar",
        "¼ cup brown sugar",
        "1 teaspoon smoked paprika",
        "½ teaspoon cayenne pepper",
        "1 teaspoon mustard powder",
        "Salt and pepper to taste",
      ],
      instructions: [
        "Sauté onion and garlic until softened.",
        "Add tomatoes and cook until broken down, about 15 minutes.",
        "Add vinegar, brown sugar, and all spices.",
        "Simmer for 30 minutes, stirring occasionally.",
        "Blend until smooth. Strain if desired.",
        "Cool and store in sterilized jars.",
      ],
      categories: ["sauces"],
    },
    {
      title: "Sage Jalapeno Cheddar Sourdough Loaf",
      slug: "sage-jalapeno-cheddar-sourdough-loaf",
      description: "A savory sourdough bread loaded with sharp cheddar, fresh sage, and spicy jalapenos.",
      prepTime: "30 minutes",
      cookTime: "45 minutes",
      totalTime: "10 hours",
      servings: "1 loaf",
      difficulty: "Advanced",
      cuisine: "American",
      cookingMethod: "Baking",
      ingredients: [
        "200g active sourdough starter",
        "400g bread flour",
        "100g whole wheat flour",
        "350g water",
        "10g salt",
        "1 cup shredded sharp cheddar cheese",
        "2 jalapenos, diced (seeds removed for less heat)",
        "2 tablespoons fresh sage, chopped",
      ],
      instructions: [
        "Mix starter, flours, and water. Autolyse for 30 minutes.",
        "Add salt and mix well.",
        "During stretch and folds, incorporate cheese, jalapenos, and sage.",
        "Perform 4 sets of stretch and folds over 2 hours.",
        "Bulk ferment 4-6 hours until doubled.",
        "Shape into a boule and place in a floured banneton.",
        "Cold proof overnight in refrigerator.",
        "Preheat Dutch oven at 500°F.",
        "Score the loaf and bake covered for 20 minutes.",
        "Remove lid, reduce to 450°F, and bake 25 more minutes.",
      ],
      categories: ["bread", "sourdough"],
    },
    {
      title: "Date Night Shrimp Cocktail",
      slug: "date-night-shrimp-cocktail",
      description: "An elegant shrimp cocktail perfect for date night or entertaining guests.",
      prepTime: "15 minutes",
      cookTime: "5 minutes",
      totalTime: "20 minutes",
      servings: "2",
      difficulty: "Easy",
      cuisine: "American",
      cookingMethod: "Sautee",
      ingredients: [
        "1 lb jumbo shrimp, peeled and deveined",
        "1 lemon, juiced",
        "Old Bay seasoning",
        "½ cup ketchup",
        "2 tablespoons prepared horseradish",
        "1 tablespoon lemon juice",
        "½ teaspoon Worcestershire sauce",
        "Hot sauce to taste",
        "Lemon wedges for serving",
      ],
      instructions: [
        "Bring a pot of salted water to boil with lemon juice and Old Bay.",
        "Add shrimp and cook 2-3 minutes until pink and curled.",
        "Transfer immediately to an ice bath to stop cooking.",
        "Mix ketchup, horseradish, lemon juice, Worcestershire, and hot sauce for cocktail sauce.",
        "Arrange chilled shrimp on a platter with cocktail sauce and lemon wedges.",
      ],
      categories: ["appetizers", "seafood", "shrimp"],
    },
    {
      title: "Sourdough Ciabatta",
      slug: "sourdough-ciabatta",
      description: "Light, airy sourdough ciabatta with large, open holes and a crispy crust.",
      prepTime: "20 minutes",
      cookTime: "25 minutes",
      totalTime: "12 hours",
      servings: "2 loaves",
      difficulty: "Advanced",
      cuisine: "Italian",
      cookingMethod: "Baking",
      ingredients: [
        "200g active sourdough starter",
        "500g bread flour",
        "400g water",
        "10g salt",
        "2 tablespoons olive oil",
      ],
      instructions: [
        "Mix starter, flour, and water into a very wet, shaggy dough.",
        "Rest 30 minutes, then add salt and olive oil.",
        "Perform stretch and folds every 30 minutes for 3 hours (6 sets).",
        "The dough should be very bubbly and jiggly.",
        "Bulk ferment 3-4 more hours until tripled in size.",
        "Gently turn dough onto a well-floured surface. Divide into 2 pieces.",
        "Gently stretch each piece into a rectangle without deflating.",
        "Transfer to parchment-lined sheet. Proof 45 minutes.",
        "Bake at 475°F with steam for 25 minutes until deeply golden.",
      ],
      categories: ["bread", "sourdough"],
    },
    {
      title: "Sourdough Chocolate Chip Walnut Pancakes",
      slug: "sourdough-chocolate-chip-walnut-pancakes",
      description: "Fluffy sourdough pancakes studded with chocolate chips and crunchy walnuts. The perfect weekend breakfast.",
      prepTime: "10 minutes",
      cookTime: "15 minutes",
      totalTime: "25 minutes",
      servings: "8 pancakes",
      difficulty: "Easy",
      cuisine: "American",
      cookingMethod: "Frying",
      ingredients: [
        "1 cup sourdough discard",
        "1 cup all-purpose flour",
        "1 cup milk",
        "1 egg",
        "2 tablespoons melted butter",
        "2 tablespoons sugar",
        "1 teaspoon baking powder",
        "½ teaspoon baking soda",
        "½ cup chocolate chips",
        "¼ cup walnuts, chopped",
        "Pinch of salt",
      ],
      instructions: [
        "Whisk together sourdough discard, milk, egg, and melted butter.",
        "In another bowl, combine flour, sugar, baking powder, baking soda, and salt.",
        "Fold dry ingredients into wet until just combined.",
        "Fold in chocolate chips and walnuts.",
        "Heat a griddle or pan over medium heat, lightly greased.",
        "Pour ¼ cup batter for each pancake.",
        "Cook until bubbles form on surface, flip and cook until golden.",
        "Serve with maple syrup and extra butter.",
      ],
      categories: ["breakfast", "sourdough"],
    },
    {
      title: "Sourdough Cinnamon Raisin Bread",
      slug: "sourdough-cinnamon-raisin-bread",
      description: "A soft, sweet sourdough bread swirled with cinnamon sugar and studded with plump raisins.",
      prepTime: "30 minutes",
      cookTime: "40 minutes",
      totalTime: "10 hours",
      servings: "1 loaf",
      difficulty: "Intermediate",
      cuisine: "American",
      cookingMethod: "Baking",
      ingredients: [
        "150g active sourdough starter",
        "400g bread flour",
        "200g milk",
        "50g butter, softened",
        "60g sugar",
        "8g salt",
        "1 cup raisins",
        "3 tablespoons cinnamon sugar (for filling)",
        "2 tablespoons butter, melted (for filling)",
      ],
      instructions: [
        "Mix starter, flour, milk, butter, sugar, and salt into a soft dough.",
        "Knead for 8-10 minutes until smooth.",
        "Fold in raisins during last minute of kneading.",
        "Bulk ferment 4-6 hours until doubled.",
        "Roll dough into a rectangle on a lightly floured surface.",
        "Brush with melted butter and sprinkle generously with cinnamon sugar.",
        "Roll tightly into a log, seam side down.",
        "Place in a greased 9x5 loaf pan. Proof 2-3 hours.",
        "Bake at 350°F for 35-40 minutes until golden.",
        "Brush top with butter while still warm.",
      ],
      categories: ["bread", "sourdough"],
    },
    {
      title: "Shrimp Fried Rice",
      slug: "shrimp-fried-rice",
      description: "Quick and flavorful shrimp fried rice loaded with vegetables and perfectly seasoned.",
      prepTime: "15 minutes",
      cookTime: "15 minutes",
      totalTime: "30 minutes",
      servings: "4",
      difficulty: "Easy",
      cuisine: "American",
      cookingMethod: "Frying",
      ingredients: [
        "1 lb shrimp, peeled and deveined",
        "4 cups cooked rice (day-old preferred)",
        "3 eggs, beaten",
        "1 cup mixed vegetables (peas, carrots, corn)",
        "3 green onions, sliced",
        "3 cloves garlic, minced",
        "3 tablespoons soy sauce",
        "1 tablespoon sesame oil",
        "2 tablespoons vegetable oil",
        "White pepper to taste",
      ],
      instructions: [
        "Heat oil in a large wok or skillet over high heat.",
        "Season shrimp with salt and pepper. Cook 2 minutes per side. Remove and set aside.",
        "Scramble eggs in the same pan. Remove and set aside.",
        "Add garlic and vegetables, stir-fry 2 minutes.",
        "Add rice, breaking up any clumps. Stir-fry 3-4 minutes.",
        "Add soy sauce, sesame oil, and white pepper.",
        "Return shrimp and eggs to the pan. Toss to combine.",
        "Garnish with green onions and serve hot.",
      ],
      categories: ["seafood", "shrimp", "rice"],
    },
    {
      title: "Simple Sourdough Sandwich Loaf",
      slug: "simple-sourdough-sandwich-loaf",
      description: "A soft, pillowy sourdough sandwich bread perfect for everyday sandwiches and toast.",
      prepTime: "20 minutes",
      cookTime: "35 minutes",
      totalTime: "10 hours",
      servings: "1 loaf",
      difficulty: "Intermediate",
      cuisine: "American",
      cookingMethod: "Baking",
      ingredients: [
        "150g active sourdough starter",
        "450g bread flour",
        "240g milk",
        "30g butter, softened",
        "30g honey",
        "9g salt",
      ],
      instructions: [
        "Mix starter, flour, milk, butter, and honey. Autolyse 30 minutes.",
        "Add salt and knead until smooth, about 10 minutes.",
        "Bulk ferment 4-6 hours with stretch and folds every hour.",
        "Shape into a tight log.",
        "Place in a greased 9x5 loaf pan seam-side down.",
        "Proof 3-4 hours until dough rises 1 inch above pan rim.",
        "Bake at 375°F for 30-35 minutes until golden.",
        "Remove from pan and cool completely on a wire rack.",
      ],
      categories: ["bread", "sourdough"],
    },
    {
      title: "Simple Yellow Split Peas Dhal",
      slug: "simple-yellow-split-peas-dhal",
      description: "A comforting Trinidad-style dhal made with yellow split peas. Simple, hearty, and full of flavor.",
      prepTime: "10 minutes",
      cookTime: "40 minutes",
      totalTime: "50 minutes",
      servings: "6",
      difficulty: "Easy",
      cuisine: "Caribbean",
      cookingMethod: "Sautee",
      ingredients: [
        "1 cup yellow split peas, rinsed",
        "4 cups water",
        "1 tablespoon oil",
        "4 cloves garlic, minced",
        "1 onion, diced",
        "2 teaspoons cumin",
        "1 teaspoon turmeric",
        "1 Scotch bonnet pepper (whole, for flavor)",
        "Salt to taste",
        "Fresh cilantro for garnish",
      ],
      instructions: [
        "Boil split peas in 4 cups water until soft and broken down, about 30 minutes.",
        "In a separate pan, heat oil and sauté garlic and onion until golden.",
        "Add cumin and turmeric, cook 1 minute until fragrant.",
        "Add the spiced onion mixture to the cooked split peas.",
        "Add whole Scotch bonnet pepper and simmer 10 minutes.",
        "Season with salt. Remove pepper before serving.",
        "Garnish with fresh cilantro. Serve with rice or roti.",
      ],
      categories: ["sides", "vegetarian"],
    },
    {
      title: "Sourdough Cheddar Biscuits",
      slug: "sourdough-cheddar-biscuits",
      description: "Flaky, buttery sourdough biscuits loaded with sharp cheddar cheese. Similar to Red Lobster biscuits!",
      prepTime: "15 minutes",
      cookTime: "15 minutes",
      totalTime: "30 minutes",
      servings: "12",
      difficulty: "Easy",
      cuisine: "American",
      cookingMethod: "Baking",
      ingredients: [
        "1 cup sourdough discard",
        "2 cups all-purpose flour",
        "1 tablespoon baking powder",
        "½ teaspoon baking soda",
        "½ cup cold butter, cubed",
        "1 cup shredded sharp cheddar",
        "¾ cup buttermilk",
        "1 teaspoon garlic powder",
        "Salt and pepper",
        "2 tablespoons melted butter (for brushing)",
        "Fresh parsley, chopped",
      ],
      instructions: [
        "Combine flour, baking powder, baking soda, garlic powder, salt, and pepper.",
        "Cut in cold butter until pea-sized pieces remain.",
        "Add sourdough discard, cheddar, and buttermilk. Mix until just combined.",
        "Drop spoonfuls of batter onto a parchment-lined baking sheet.",
        "Bake at 425°F for 12-15 minutes until golden.",
        "Brush with melted butter and sprinkle with parsley while warm.",
      ],
      categories: ["bread", "sourdough", "biscuits"],
    },
    {
      title: "Olive Oil Dip For Sourdough Bread",
      slug: "olive-oil-dip-for-sourdough-bread",
      description: "A simple, elegant olive oil dip with herbs and Parmesan, perfect for dipping crusty sourdough bread.",
      prepTime: "5 minutes",
      cookTime: "0 minutes",
      totalTime: "5 minutes",
      servings: "4",
      difficulty: "Easy",
      cuisine: "Italian",
      cookingMethod: "Sautee",
      ingredients: [
        "½ cup extra virgin olive oil",
        "2 tablespoons balsamic vinegar",
        "3 cloves garlic, minced",
        "1 teaspoon dried oregano",
        "1 teaspoon dried basil",
        "½ teaspoon red pepper flakes",
        "2 tablespoons grated Parmesan cheese",
        "Salt and freshly ground pepper",
        "Fresh herbs for garnish",
      ],
      instructions: [
        "Pour olive oil into a shallow bowl or plate.",
        "Add balsamic vinegar.",
        "Sprinkle garlic, oregano, basil, and red pepper flakes over the oil.",
        "Add grated Parmesan and season with salt and pepper.",
        "Garnish with fresh herbs.",
        "Serve with sliced sourdough bread.",
      ],
      categories: ["appetizers", "sauces"],
    },
    {
      title: "Stewed Pumpkin (Trinidad Style)",
      slug: "stewed-pumpkin-trinidad-style",
      description: "A simple, savory Caribbean-style stewed pumpkin that makes a perfect side dish.",
      prepTime: "10 minutes",
      cookTime: "25 minutes",
      totalTime: "35 minutes",
      servings: "4",
      difficulty: "Easy",
      cuisine: "Caribbean",
      cookingMethod: "Sautee",
      ingredients: [
        "2 lbs Caribbean pumpkin (calabaza), peeled and cubed",
        "2 tablespoons oil",
        "1 onion, diced",
        "3 cloves garlic, minced",
        "1 tablespoon brown sugar",
        "½ cup coconut milk",
        "Fresh thyme",
        "Salt and pepper to taste",
        "1 Scotch bonnet pepper (optional)",
      ],
      instructions: [
        "Heat oil in a large pot. Sauté onion and garlic until fragrant.",
        "Add brown sugar and stir until dissolved.",
        "Add pumpkin cubes and stir to coat.",
        "Add coconut milk, thyme, and Scotch bonnet pepper if using.",
        "Cover and simmer for 20-25 minutes until pumpkin is tender.",
        "Season with salt and pepper. Some pieces will break down creating a thick sauce.",
        "Serve as a side dish with rice.",
      ],
      categories: ["sides", "vegetarian"],
    },
    {
      title: "Sourdough English Muffins",
      slug: "sourdough-english-muffins",
      description: "Classic English muffins with a sourdough twist. Full of nooks and crannies for butter and jam.",
      prepTime: "20 minutes",
      cookTime: "20 minutes",
      totalTime: "8 hours",
      servings: "10",
      difficulty: "Intermediate",
      cuisine: "American",
      cookingMethod: "Frying",
      ingredients: [
        "150g active sourdough starter",
        "300g all-purpose flour",
        "150g milk",
        "30g butter, melted",
        "20g sugar",
        "5g salt",
        "Cornmeal for dusting",
      ],
      instructions: [
        "Mix all ingredients (except cornmeal) into a soft dough.",
        "Knead 5 minutes until smooth.",
        "Bulk ferment 4-6 hours until doubled.",
        "Roll out dough to ¾ inch thickness on a floured surface.",
        "Cut rounds with a 3-inch cutter. Re-roll scraps.",
        "Dust with cornmeal on both sides.",
        "Place on parchment-lined tray. Proof 1-2 hours.",
        "Cook on a dry griddle or skillet over medium-low heat.",
        "Cook 7-8 minutes per side until golden brown and cooked through.",
        "Split with a fork to preserve the nooks and crannies.",
      ],
      categories: ["bread", "sourdough", "breakfast"],
    },
    {
      title: "Grilled Honey Cinnamon Apple Wedges",
      slug: "grilled-honey-cinnamon-apple-wedges",
      description: "Sweet, caramelized grilled apple wedges drizzled with honey and cinnamon. A healthy dessert or snack.",
      prepTime: "10 minutes",
      cookTime: "8 minutes",
      totalTime: "18 minutes",
      servings: "4",
      difficulty: "Easy",
      cuisine: "American",
      cookingMethod: "Grilling",
      ingredients: [
        "4 large apples, cored and cut into wedges",
        "2 tablespoons honey",
        "1 teaspoon cinnamon",
        "1 tablespoon melted butter",
        "Pinch of nutmeg",
      ],
      instructions: [
        "Preheat grill to medium-high heat.",
        "Toss apple wedges with melted butter, honey, cinnamon, and nutmeg.",
        "Grill apple wedges 3-4 minutes per side until tender with grill marks.",
        "Drizzle with additional honey before serving.",
      ],
      categories: ["desserts", "snacks"],
    },
    {
      title: "Grilled Honey Cinnamon Pineapple Spears",
      slug: "grilled-honey-cinnamon-pineapple-spears",
      description: "Juicy grilled pineapple spears with a honey-cinnamon glaze. Perfect summer treat.",
      prepTime: "10 minutes",
      cookTime: "8 minutes",
      totalTime: "18 minutes",
      servings: "4",
      difficulty: "Easy",
      cuisine: "American",
      cookingMethod: "Grilling",
      ingredients: [
        "1 fresh pineapple, cut into spears",
        "2 tablespoons honey",
        "1 teaspoon cinnamon",
        "1 tablespoon melted butter",
        "Pinch of cayenne pepper (optional)",
      ],
      instructions: [
        "Preheat grill to medium-high heat.",
        "Mix honey, melted butter, cinnamon, and cayenne.",
        "Brush pineapple spears with the honey mixture.",
        "Grill 3-4 minutes per side until caramelized.",
        "Serve warm with remaining honey mixture drizzled on top.",
      ],
      categories: ["desserts", "snacks"],
    },
    {
      title: "Cast Iron Cornbread",
      slug: "cast-iron-cornbread",
      description: "Golden, crispy-edged cornbread baked in a cast iron skillet. A Southern classic.",
      prepTime: "10 minutes",
      cookTime: "25 minutes",
      totalTime: "35 minutes",
      servings: "8",
      difficulty: "Easy",
      cuisine: "Southern",
      cookingMethod: "Baking",
      ingredients: [
        "1 cup yellow cornmeal",
        "1 cup all-purpose flour",
        "¼ cup sugar",
        "1 tablespoon baking powder",
        "½ teaspoon salt",
        "1 cup buttermilk",
        "⅓ cup melted butter",
        "2 eggs",
        "2 tablespoons butter (for skillet)",
      ],
      instructions: [
        "Preheat oven to 425°F. Place 2 tablespoons butter in a 10-inch cast iron skillet and put in oven.",
        "Mix cornmeal, flour, sugar, baking powder, and salt.",
        "Whisk together buttermilk, melted butter, and eggs.",
        "Combine wet and dry ingredients until just mixed.",
        "Carefully remove hot skillet from oven. Swirl melted butter.",
        "Pour batter into hot skillet.",
        "Bake 20-25 minutes until golden and a toothpick comes out clean.",
        "Let cool 5 minutes before slicing. Serve with butter and honey.",
      ],
      categories: ["bread", "sides"],
    },
    {
      title: "Sriracha Ketchup",
      slug: "sriracha-ketchup",
      description: "A quick and easy spicy ketchup that adds kick to burgers, fries, and more.",
      prepTime: "5 minutes",
      cookTime: "0 minutes",
      totalTime: "5 minutes",
      servings: "1 cup",
      difficulty: "Easy",
      cuisine: "American",
      cookingMethod: "Sautee",
      ingredients: [
        "½ cup ketchup",
        "2 tablespoons sriracha (adjust to taste)",
        "1 tablespoon honey",
        "1 teaspoon lime juice",
        "½ teaspoon garlic powder",
      ],
      instructions: [
        "Combine all ingredients in a bowl.",
        "Whisk until smooth and well combined.",
        "Taste and adjust sriracha for desired heat level.",
        "Refrigerate until ready to serve.",
      ],
      categories: ["sauces"],
    },
    {
      title: "Butter Fried Swai",
      slug: "butter-fried-swai",
      description: "Pan-fried swai fillets in golden butter with a light, crispy coating.",
      prepTime: "10 minutes",
      cookTime: "10 minutes",
      totalTime: "20 minutes",
      servings: "4",
      difficulty: "Easy",
      cuisine: "American",
      cookingMethod: "Frying",
      ingredients: [
        "4 swai fillets",
        "½ cup all-purpose flour",
        "1 teaspoon garlic powder",
        "1 teaspoon paprika",
        "Salt and pepper",
        "4 tablespoons butter",
        "Lemon wedges for serving",
        "Fresh parsley, chopped",
      ],
      instructions: [
        "Pat swai fillets dry with paper towels.",
        "Mix flour, garlic powder, paprika, salt, and pepper.",
        "Dredge each fillet in the seasoned flour.",
        "Melt butter in a large skillet over medium-high heat.",
        "Cook fillets 3-4 minutes per side until golden and flaky.",
        "Squeeze lemon over fish and garnish with parsley.",
      ],
      categories: ["seafood"],
    },
    {
      title: "Jerk Shrimp",
      slug: "jerk-shrimp",
      description: "Spicy, smoky Caribbean jerk-seasoned shrimp. Bold flavors in every bite.",
      prepTime: "15 minutes",
      cookTime: "8 minutes",
      totalTime: "23 minutes",
      servings: "4",
      difficulty: "Easy",
      cuisine: "Caribbean",
      cookingMethod: "Grilling",
      ingredients: [
        "1 lb large shrimp, peeled and deveined",
        "2 tablespoons jerk seasoning",
        "2 tablespoons olive oil",
        "1 tablespoon lime juice",
        "2 cloves garlic, minced",
        "1 tablespoon honey",
        "Fresh cilantro for garnish",
        "Lime wedges for serving",
      ],
      instructions: [
        "Mix jerk seasoning, olive oil, lime juice, garlic, and honey.",
        "Toss shrimp in the marinade. Let sit 10 minutes.",
        "Thread shrimp onto skewers (if grilling) or use a hot skillet.",
        "Cook 2-3 minutes per side until pink and slightly charred.",
        "Garnish with cilantro and serve with lime wedges.",
      ],
      categories: ["seafood", "shrimp", "appetizers"],
    },
    {
      title: "Pineapple Mango Salsa",
      slug: "pineapple-mango-salsa",
      description: "A fresh, tropical fruit salsa that pairs perfectly with grilled fish, chicken, or chips.",
      prepTime: "15 minutes",
      cookTime: "0 minutes",
      totalTime: "15 minutes",
      servings: "4",
      difficulty: "Easy",
      cuisine: "Latino",
      cookingMethod: "Sautee",
      ingredients: [
        "1 cup fresh pineapple, diced",
        "1 ripe mango, diced",
        "½ red onion, finely diced",
        "1 jalapeno, seeded and minced",
        "¼ cup fresh cilantro, chopped",
        "2 tablespoons lime juice",
        "Salt to taste",
      ],
      instructions: [
        "Combine pineapple, mango, red onion, jalapeno, and cilantro in a bowl.",
        "Add lime juice and salt.",
        "Toss gently to combine.",
        "Refrigerate 30 minutes for flavors to meld.",
        "Serve with tortilla chips or alongside grilled proteins.",
      ],
      categories: ["sauces", "appetizers"],
    },
    {
      title: "Belgian Waffles",
      slug: "belgian-waffles",
      description: "Light, crispy Belgian waffles with deep pockets perfect for holding syrup and toppings.",
      prepTime: "15 minutes",
      cookTime: "20 minutes",
      totalTime: "35 minutes",
      servings: "6",
      difficulty: "Easy",
      cuisine: "American",
      cookingMethod: "Baking",
      ingredients: [
        "2 cups all-purpose flour",
        "¾ cup milk",
        "½ cup melted butter",
        "2 eggs, separated",
        "1 tablespoon sugar",
        "2 teaspoons baking powder",
        "1 teaspoon vanilla extract",
        "½ teaspoon salt",
        "Berries, whipped cream, and maple syrup for serving",
      ],
      instructions: [
        "Whisk together flour, sugar, baking powder, and salt.",
        "In another bowl, combine milk, melted butter, egg yolks, and vanilla.",
        "Mix wet and dry ingredients until just combined.",
        "Beat egg whites until stiff peaks form.",
        "Gently fold egg whites into the batter.",
        "Preheat waffle iron and lightly grease.",
        "Pour batter into waffle iron and cook until golden and crispy.",
        "Serve with berries, whipped cream, and maple syrup.",
      ],
      categories: ["breakfast"],
    },
    {
      title: "Coconut Ice Cream",
      slug: "coconut-ice-cream",
      description: "Creamy, rich homemade coconut ice cream. A tropical treat that's dairy-free friendly.",
      prepTime: "15 minutes",
      cookTime: "0 minutes",
      totalTime: "4 hours",
      servings: "6",
      difficulty: "Easy",
      cuisine: "Caribbean",
      cookingMethod: "Sautee",
      ingredients: [
        "2 cans (14 oz each) full-fat coconut milk",
        "¾ cup sugar",
        "1 cup shredded coconut, toasted",
        "1 teaspoon vanilla extract",
        "Pinch of salt",
      ],
      instructions: [
        "Whisk coconut milk, sugar, vanilla, and salt until sugar dissolves.",
        "Chill mixture in refrigerator for at least 2 hours.",
        "Pour into ice cream maker and churn according to manufacturer instructions.",
        "Fold in toasted shredded coconut in the last few minutes of churning.",
        "Transfer to a freezer-safe container and freeze until firm, about 2 hours.",
        "Let sit at room temperature 5 minutes before scooping.",
      ],
      categories: ["desserts"],
    },
    {
      title: "Easy 4 Ingredient No Knead Rolls",
      slug: "easy-4-ingredient-no-knead-rolls",
      description: "The easiest dinner rolls you'll ever make. Just 4 ingredients and no kneading required.",
      prepTime: "10 minutes",
      cookTime: "20 minutes",
      totalTime: "2 hours 30 minutes",
      servings: "12",
      difficulty: "Easy",
      cuisine: "American",
      cookingMethod: "Baking",
      ingredients: [
        "3 cups all-purpose flour",
        "1½ cups warm water",
        "2¼ teaspoons active dry yeast",
        "1 teaspoon salt",
      ],
      instructions: [
        "Dissolve yeast in warm water. Let sit 5 minutes until foamy.",
        "Add flour and salt. Mix until a shaggy dough forms.",
        "Cover and let rise 2 hours until doubled.",
        "Grease a muffin tin or baking pan.",
        "Scoop dough into portions and place in prepared pan.",
        "Bake at 400°F for 18-20 minutes until golden brown.",
      ],
      categories: ["bread"],
    },
    {
      title: "Stewed Red Beans (Trinidad Style)",
      slug: "stewed-red-beans-trinidad-style",
      description: "Hearty Trinidad-style stewed red beans in a rich, savory sauce. Perfect with rice.",
      prepTime: "10 minutes",
      cookTime: "45 minutes",
      totalTime: "55 minutes",
      servings: "6",
      difficulty: "Easy",
      cuisine: "Caribbean",
      cookingMethod: "Sautee",
      ingredients: [
        "2 cans (15 oz) red kidney beans, drained",
        "1 tablespoon oil",
        "1 onion, diced",
        "3 cloves garlic, minced",
        "1 tablespoon brown sugar",
        "1 cup coconut milk",
        "Fresh thyme sprigs",
        "1 teaspoon cumin",
        "Salt and pepper to taste",
        "1 Scotch bonnet pepper (whole)",
      ],
      instructions: [
        "Heat oil in a pot over medium heat.",
        "Add brown sugar and let it caramelize slightly.",
        "Add onion and garlic, sauté until softened.",
        "Add beans, coconut milk, thyme, cumin, and Scotch bonnet pepper.",
        "Simmer for 30-40 minutes, stirring occasionally, until thick and saucy.",
        "Season with salt and pepper. Remove Scotch bonnet before serving.",
        "Serve over white rice.",
      ],
      categories: ["sides", "vegetarian"],
    },
    {
      title: "Italian Herb Sourdough Discard Crackers",
      slug: "italian-herb-sourdough-discard-crackers",
      description: "Thin, crispy crackers made with sourdough discard and Italian herbs. A great snack!",
      prepTime: "10 minutes",
      cookTime: "15 minutes",
      totalTime: "25 minutes",
      servings: "30 crackers",
      difficulty: "Easy",
      cuisine: "Italian",
      cookingMethod: "Baking",
      ingredients: [
        "1 cup sourdough discard",
        "¼ cup olive oil",
        "1 teaspoon Italian seasoning",
        "½ teaspoon garlic powder",
        "½ teaspoon flaky sea salt",
        "Fresh rosemary (optional)",
      ],
      instructions: [
        "Mix sourdough discard, olive oil, Italian seasoning, and garlic powder.",
        "Spread very thinly on a parchment-lined baking sheet.",
        "Sprinkle with flaky sea salt and fresh rosemary.",
        "Bake at 350°F for 12-15 minutes until golden and crispy.",
        "Let cool completely, then break into irregular pieces.",
        "Store in an airtight container.",
      ],
      categories: ["snacks", "sourdough"],
    },
    {
      title: "Sourdough Cranberry Orange Muffins",
      slug: "sourdough-cranberry-orange-muffins",
      description: "Tender, moist muffins with tart cranberries and bright orange zest, made with sourdough discard.",
      prepTime: "15 minutes",
      cookTime: "22 minutes",
      totalTime: "37 minutes",
      servings: "12",
      difficulty: "Easy",
      cuisine: "American",
      cookingMethod: "Baking",
      ingredients: [
        "1 cup sourdough discard",
        "1½ cups all-purpose flour",
        "½ cup sugar",
        "1 teaspoon baking powder",
        "½ teaspoon baking soda",
        "¼ teaspoon salt",
        "1 egg",
        "⅓ cup melted butter",
        "½ cup milk",
        "1 teaspoon vanilla extract",
        "Zest of 1 orange",
        "1 cup fresh or frozen cranberries",
      ],
      instructions: [
        "Preheat oven to 375°F. Line a muffin tin with liners.",
        "Mix flour, sugar, baking powder, baking soda, and salt.",
        "Whisk together sourdough discard, egg, butter, milk, vanilla, and orange zest.",
        "Fold wet ingredients into dry until just combined.",
        "Gently fold in cranberries.",
        "Divide batter among muffin cups.",
        "Bake 20-22 minutes until a toothpick comes out clean.",
        "Cool 5 minutes before removing from tin.",
      ],
      categories: ["breakfast", "sourdough"],
    },
    {
      title: "20 min Sourdough Pancakes",
      slug: "20-min-sourdough-pancakes",
      description: "Quick and easy sourdough pancakes ready in just 20 minutes. A perfect use for sourdough discard.",
      prepTime: "5 minutes",
      cookTime: "15 minutes",
      totalTime: "20 minutes",
      servings: "8",
      difficulty: "Easy",
      cuisine: "American",
      cookingMethod: "Frying",
      ingredients: [
        "1 cup sourdough discard",
        "1 cup all-purpose flour",
        "1 cup milk",
        "1 egg",
        "2 tablespoons sugar",
        "2 tablespoons melted butter",
        "1 teaspoon baking powder",
        "½ teaspoon baking soda",
        "Pinch of salt",
      ],
      instructions: [
        "Whisk together sourdough discard, milk, egg, and melted butter.",
        "Add flour, sugar, baking powder, baking soda, and salt.",
        "Mix until just combined. Don't overmix - a few lumps are fine.",
        "Heat a griddle over medium heat and lightly grease.",
        "Pour ¼ cup batter per pancake.",
        "Cook until bubbles form on surface and edges are set, about 2 minutes.",
        "Flip and cook 1-2 more minutes until golden.",
        "Serve with maple syrup and fresh fruit.",
      ],
      categories: ["breakfast", "sourdough"],
    },
    {
      title: "SMH Biscuits",
      slug: "smh-biscuits",
      description: "Soft, melt-in-your-mouth homemade biscuits. So good they'll make you shake your head!",
      prepTime: "15 minutes",
      cookTime: "15 minutes",
      totalTime: "30 minutes",
      servings: "10",
      difficulty: "Easy",
      cuisine: "Southern",
      cookingMethod: "Baking",
      ingredients: [
        "2 cups all-purpose flour",
        "1 tablespoon baking powder",
        "1 teaspoon sugar",
        "½ teaspoon salt",
        "½ cup cold butter, cubed",
        "¾ cup cold buttermilk",
        "2 tablespoons melted butter (for brushing)",
      ],
      instructions: [
        "Preheat oven to 450°F.",
        "Whisk flour, baking powder, sugar, and salt together.",
        "Cut in cold butter until mixture resembles coarse crumbs.",
        "Add buttermilk and stir until just combined.",
        "Turn dough onto floured surface. Pat to 1-inch thickness.",
        "Fold dough in half, pat out again. Repeat 3 times for flaky layers.",
        "Cut with 2.5-inch biscuit cutter. Don't twist the cutter!",
        "Place on baking sheet touching each other. Bake 12-15 minutes.",
        "Brush with melted butter immediately out of the oven.",
      ],
      categories: ["bread", "biscuits"],
    },
    {
      title: "Fragrant Lemon Herb Salmon",
      slug: "fragrant-lemon-herb-salmon",
      description: "Perfectly baked salmon with fresh lemon, herbs, and garlic. Simple, elegant, and delicious.",
      prepTime: "10 minutes",
      cookTime: "15 minutes",
      totalTime: "25 minutes",
      servings: "4",
      difficulty: "Easy",
      cuisine: "American",
      cookingMethod: "Baking",
      ingredients: [
        "4 salmon fillets",
        "2 lemons (1 sliced, 1 juiced)",
        "4 cloves garlic, minced",
        "2 tablespoons olive oil",
        "1 tablespoon fresh dill, chopped",
        "1 tablespoon fresh parsley, chopped",
        "Salt and pepper",
      ],
      instructions: [
        "Preheat oven to 400°F. Line a baking sheet with foil.",
        "Place salmon fillets on the prepared sheet.",
        "Drizzle with olive oil and lemon juice.",
        "Top with minced garlic, dill, and parsley.",
        "Season with salt and pepper. Lay lemon slices on top.",
        "Bake 12-15 minutes until salmon flakes easily with a fork.",
        "Serve immediately with steamed vegetables or rice.",
      ],
      categories: ["seafood", "salmon"],
    },
    {
      title: "Crispy Air Fried Zucchini Fries",
      slug: "crispy-air-fried-zucchini-fries",
      description: "Crunchy on the outside, tender on the inside. A healthier alternative to regular fries.",
      prepTime: "15 minutes",
      cookTime: "12 minutes",
      totalTime: "27 minutes",
      servings: "4",
      difficulty: "Easy",
      cuisine: "American",
      cookingMethod: "Air Frying",
      ingredients: [
        "3 medium zucchini, cut into fry shapes",
        "½ cup all-purpose flour",
        "2 eggs, beaten",
        "1 cup panko breadcrumbs",
        "½ cup grated Parmesan cheese",
        "1 teaspoon garlic powder",
        "1 teaspoon Italian seasoning",
        "Salt and pepper",
        "Cooking spray",
        "Marinara sauce for dipping",
      ],
      instructions: [
        "Set up breading station: flour, beaten eggs, and panko mixed with Parmesan, garlic powder, and Italian seasoning.",
        "Dredge zucchini in flour, dip in egg, then coat in panko mixture.",
        "Preheat air fryer to 400°F.",
        "Arrange zucchini in a single layer. Spray with cooking spray.",
        "Air fry 10-12 minutes, flipping halfway, until golden and crispy.",
        "Serve immediately with warm marinara sauce.",
      ],
      categories: ["sides", "snacks", "vegetarian"],
    },
    {
      title: "Broiled Sweet Thai Chili Salmon and Spinach",
      slug: "broiled-sweet-thai-chili-salmon-and-spinach",
      description: "Quick broiled salmon glazed with sweet Thai chili sauce served on a bed of wilted spinach.",
      prepTime: "10 minutes",
      cookTime: "12 minutes",
      totalTime: "22 minutes",
      servings: "4",
      difficulty: "Easy",
      cuisine: "American",
      cookingMethod: "Baking",
      ingredients: [
        "4 salmon fillets",
        "¼ cup sweet Thai chili sauce",
        "2 tablespoons soy sauce",
        "1 tablespoon lime juice",
        "2 cloves garlic, minced",
        "1 tablespoon ginger, grated",
        "6 cups fresh spinach",
        "1 tablespoon olive oil",
        "Sesame seeds for garnish",
        "Green onions for garnish",
      ],
      instructions: [
        "Mix Thai chili sauce, soy sauce, lime juice, garlic, and ginger.",
        "Place salmon on a foil-lined broiler pan. Brush generously with glaze.",
        "Broil on high for 8-10 minutes until caramelized and cooked through.",
        "Meanwhile, wilt spinach in olive oil over medium heat.",
        "Season spinach with salt and pepper.",
        "Serve salmon over spinach. Drizzle with remaining glaze.",
        "Garnish with sesame seeds and sliced green onions.",
      ],
      categories: ["seafood", "salmon"],
    },
    {
      title: "Crispy Chunky Granola",
      slug: "crispy-chunky-granola",
      description: "Crunchy, chunky homemade granola with big clusters, nuts, fruit, and seeds. So much better than store-bought!",
      prepTime: "10 minutes",
      cookTime: "30 minutes",
      totalTime: "40 minutes",
      servings: "8",
      difficulty: "Easy",
      cuisine: "American",
      cookingMethod: "Baking",
      ingredients: [
        "3 cups old-fashioned oats",
        "1 cup mixed nuts (almonds, pecans, walnuts), chopped",
        "½ cup honey or maple syrup",
        "¼ cup coconut oil, melted",
        "½ cup shredded coconut",
        "¼ cup sunflower seeds",
        "1 teaspoon vanilla extract",
        "1 teaspoon cinnamon",
        "½ teaspoon salt",
        "½ cup dried fruit (cranberries, raisins)",
      ],
      instructions: [
        "Preheat oven to 325°F. Line a baking sheet with parchment paper.",
        "Mix oats, nuts, coconut, sunflower seeds, cinnamon, and salt.",
        "Warm honey and coconut oil together. Add vanilla.",
        "Pour liquid over dry ingredients and mix well until everything is coated.",
        "Press mixture firmly onto baking sheet in an even layer. Don't stir during baking!",
        "Bake 25-30 minutes until edges are golden.",
        "Let cool completely without breaking up. Add dried fruit.",
        "Break into chunks. Store in airtight container.",
      ],
      categories: ["breakfast", "snacks"],
    },
    {
      title: "Chicken Tinga",
      slug: "chicken-tinga",
      description: "Smoky, spicy shredded chicken in a chipotle tomato sauce. Perfect for tacos, tostadas, or burritos.",
      prepTime: "15 minutes",
      cookTime: "30 minutes",
      totalTime: "45 minutes",
      servings: "6",
      difficulty: "Easy",
      cuisine: "Latino",
      cookingMethod: "Sautee",
      ingredients: [
        "2 lbs chicken breast or thighs",
        "1 can (14 oz) fire-roasted diced tomatoes",
        "2-3 chipotle peppers in adobo sauce",
        "1 onion, sliced",
        "3 cloves garlic, minced",
        "1 tablespoon oil",
        "1 teaspoon cumin",
        "1 teaspoon oregano",
        "Salt and pepper",
        "Tostadas, avocado, and queso fresco for serving",
      ],
      instructions: [
        "Poach chicken in salted water until cooked through, about 20 minutes. Shred and set aside.",
        "Blend tomatoes and chipotle peppers until smooth.",
        "Heat oil in a large skillet. Sauté onion until caramelized.",
        "Add garlic, cumin, and oregano. Cook 1 minute.",
        "Pour in chipotle-tomato sauce. Simmer 5 minutes.",
        "Add shredded chicken and stir to coat. Cook 5 more minutes.",
        "Serve on tostadas topped with avocado and queso fresco.",
      ],
      categories: ["chicken", "mexican"],
    },
    {
      title: "The Legit Jamaican Coco Bread Recipe",
      slug: "the-legit-jamaican-coco-bread-recipe",
      description: "Soft, buttery Jamaican coco bread with a hint of coconut milk. The perfect accompaniment to any Caribbean meal.",
      prepTime: "30 minutes",
      cookTime: "20 minutes",
      totalTime: "2 hours 50 minutes",
      servings: "8",
      difficulty: "Intermediate",
      cuisine: "Caribbean",
      cookingMethod: "Baking",
      ingredients: [
        "3½ cups all-purpose flour",
        "¼ cup sugar",
        "1 teaspoon salt",
        "2¼ teaspoons active dry yeast",
        "½ cup coconut milk",
        "½ cup warm water",
        "3 tablespoons butter, melted",
        "Additional butter for brushing and folding",
      ],
      instructions: [
        "Dissolve yeast in warm water with a pinch of sugar. Let foam 10 minutes.",
        "Mix flour, sugar, and salt in a large bowl.",
        "Add yeast mixture, coconut milk, and melted butter.",
        "Knead for 10 minutes until smooth and elastic.",
        "Place in a greased bowl, cover, and let rise 1.5 hours until doubled.",
        "Punch down and divide into 8 equal pieces.",
        "Roll each piece into an oval shape.",
        "Brush with melted butter, fold in half, and press edges gently.",
        "Place on a greased baking sheet. Let rise 30 minutes.",
        "Bake at 350°F for 18-20 minutes until golden.",
        "Brush with butter immediately out of the oven.",
      ],
      categories: ["bread"],
    },
  ];

  // Create recipes with categories
  for (const recipe of recipes) {
    const { categories: recipeCats, ...recipeData } = recipe;
    const existing = await prisma.recipe.findUnique({
      where: { slug: recipeData.slug },
    });
    if (existing) continue;

    await prisma.recipe.create({
      data: {
        ...recipeData,
        ingredients: JSON.stringify(recipeData.ingredients),
        instructions: JSON.stringify(recipeData.instructions),
        nutrition: recipeData.nutrition
          ? JSON.stringify(recipeData.nutrition)
          : null,
        categories: {
          create: recipeCats
            .filter((slug) => catMap[slug])
            .map((slug) => ({ categoryId: catMap[slug] })),
        },
      },
    });
  }

  console.log("Seed completed successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
